### ISSUE TITLE
[question] how to render original color?

### ISSUE THREAD

**Issue by ywpkwon** [panmari/stanford-shapenet-renderer#1]
Thanks for this great tool. May I ask a question?

The `render-blender.py` generates `abc.png`, `abc_albedo.png`, `abc._depth.png`, `abc_normal.png`. The default `abc.png` generates a gray-ish model without any original colors (maybe given from .mtl file?). Is there an easy way to render models with original colors given from Shape net?
(Sorry, I do not have much background about rendering and Blender.)

**Comment by panmari** [comment]
Hi there!
Happy to hear that it's (mostly) working for you. I remember having a similar issue in the chair dataset for some models. I simply chose to exclude the models without texture/colors in the end. 

Do you have an example of a model that doesn't work? We could open it manually in blender and see what's wrong.

**Comment by ywpkwon** [comment]
Thanks! I was not sure if it was an mlt loading problem or if it was the original model by itself. I will let you know if I found one. (Sorry, I am so new to Blender.)

**Comment by panmari** [comment]
Let's do that!
Did you figure out your problem regarding the light sources? Might be good to document if there's a general issue.

**Comment by ywpkwon** [comment]
Sure. I just tried a very naive solution to it. Since it is a different subject, I will post it separately. Thanks for your consideration.

**Comment by MalihaUCF** [comment]
@ywpkwon @panmari   I am facing a similar issue, I want RGB images, not black and white, can you suggest how to solve it? rest is working fine :)
