### ISSUE TITLE
Invalid clnors in this fan!

### ISSUE THREAD

**Issue by jsikyoon** [panmari/stanford-shapenet-renderer#10]
Hi

Thank you for your code :)

I tried to use your repo on ShapeNetSem obj files, however I got almost gray imgs with **Invalid clnors in this fan!** error.

Could I know how I can get images?

Bellowed line is an example I tried to use.

I used default setting on your repo.

blender --background --python render_blender.py -- --output_folder tmp/ ShapeNetSem/models/3b70e61e3606b22edf18ae79c62fd05e.obj

Thanks.
Jaesik.

**Comment by panmari** [comment]
This must be an issue with your obj file. Please provide your obj file if you want me to look into this.

Closing for now.
