### ISSUE TITLE
Not getting RGB or composite images?

### ISSUE THREAD

**Issue by MalihaUCF** [panmari/stanford-shapenet-renderer#12]
Hi, I have tryng to run this code for rendering Shapenet datasets for quite sometime. I have tried many things but somehow I get only these 4 type of images.

![shapnet_render](https://user-images.githubusercontent.com/42460909/47933478-0df90e80-deab-11e8-97ba-f2078f759f97.png)

Can you please tell how do I obtain fully colored images , really need this for a project desperately, like these maybe

![000_cl_0_20_336_-1](https://user-images.githubusercontent.com/42460909/47933619-6a5c2e00-deab-11e8-924d-d5bb9bc78e7e.png)

thank you

**Comment by panmari** [comment]
Did you try opening the file in blender directly? Were there any errors? By running without the `--background` flag, the blender instance stays open for you to investigate:

    blender --background --python render_blender.py -- --output_folder /tmp path_to_model.obj

Unfortunately this is almost impossible for me to debug without the mesh definition.

**Comment by MalihaUCF** [comment]
thank you so much for replying, so here it is
In just tried that, I do see these lines during execution


Rotation 216.0, 3.7699111843077517
Fra:1 Mem:47.44M (0.00M, Peak 48.37M) | Time:00:00.02 | Preparing Scene data
Fra:1 Mem:50.76M (0.00M, Peak 50.82M) | Time:00:00.03 | Preparing Scene data
Fra:1 Mem:50.76M (0.00M, Peak 50.82M) | Time:00:00.03 | Creating Shadowbuffers
Fra:1 Mem:50.76M (0.00M, Peak 50.82M) | Time:00:00.03 | Raytree.. preparing
Fra:1 Mem:53.80M (0.00M, Peak 53.80M) | Time:00:00.03 | Raytree.. building
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Raytree finished
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Creating Environment maps
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Caching Point Densities
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Sce: Scene Ve:24273 Fa:22152 La:2
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Loading voxel datasets
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Sce: Scene Ve:24273 Fa:22152 La:2
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Sce: Scene Ve:24273 Fa:22152 La:2
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Volume preprocessing
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Sce: Scene Ve:24273 Fa:22152 La:2
Fra:1 Mem:53.65M (0.00M, Peak 58.41M) | Time:00:00.08 | Sce: Scene Ve:24273 Fa:22152 La:2
Fra:1 Mem:56.23M (0.00M, Peak 58.41M) | Time:00:00.09 | Scene, Part 2-100
Fra:1 Mem:56.28M (0.00M, Peak 58.41M) | Time:00:00.10 | Scene, Part 3-100
Fra:1 Mem:56.32M (0.00M, Peak 58.41M) | Time:00:00.10 | Scene, Part 1-100
Fra:1 Mem:56.32M (0.00M, Peak 58.41M) | Time:00:00.10 | Scene, Part 5-100
Fra:1 Mem:56.16M (0.00M, Peak 58.41M) | Time:00:00.10 | Scene, Part 4-100
Fra:1 Mem:55.45M (0.00M, Peak 58.41M) | Time:00:00.11 | Scene, Part 6-100
Fra:1 Mem:55.55M (0.00M, Peak 58.41M) | Time:00:00.11 | Scene, Part 8-100
Fra:1 Mem:55.77M (0.00M, Peak 58.41M) | Time:00:00.11 | Scene, Part 7-100
Fra:1 Mem:55.70M (0.00M, Peak 58.41M) | Time:00:00.11 | Scene, Part 9-100
Fra:1 Mem:55.70M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 11-100
Fra:1 Mem:55.73M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 12-100
Fra:1 Mem:55.80M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 14-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 10-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 13-100
Fra:1 Mem:55.77M (0.00M, Peak 58.41M) | Time:00:00.12 | Scene, Part 15-100
Fra:1 Mem:55.07M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 18-100
Fra:1 Mem:54.86M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 17-100
Fra:1 Mem:55.68M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 19-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 16-100
Fra:1 Mem:55.73M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 20-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 22-100
Fra:1 Mem:55.50M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 24-100
Fra:1 Mem:55.52M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 25-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.13 | Scene, Part 23-100
Fra:1 Mem:55.29M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 28-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 21-100
Fra:1 Mem:55.45M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 27-100
Fra:1 Mem:55.39M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 29-100
Fra:1 Mem:55.18M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 26-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 30-100
Fra:1 Mem:55.71M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 31-100
Fra:1 Mem:55.27M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 32-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 34-100
Fra:1 Mem:55.16M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 36-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 37-100
Fra:1 Mem:55.39M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 35-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 38-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 40-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 41-100
Fra:1 Mem:55.27M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 33-100
Fra:1 Mem:55.54M (0.00M, Peak 58.41M) | Time:00:00.14 | Scene, Part 42-100
Fra:1 Mem:55.11M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 44-100
Fra:1 Mem:55.23M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 45-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 39-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 46-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 43-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 48-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 47-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 49-100
Fra:1 Mem:55.55M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 50-100
Fra:1 Mem:54.90M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 53-100
Fra:1 Mem:55.61M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 51-100
Fra:1 Mem:55.59M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 52-100
Fra:1 Mem:55.55M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 54-100
Fra:1 Mem:55.27M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 57-100
Fra:1 Mem:55.13M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 56-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 55-100
Fra:1 Mem:55.71M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 58-100
Fra:1 Mem:55.39M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 59-100
Fra:1 Mem:55.18M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 60-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 61-100
Fra:1 Mem:55.57M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 62-100
Fra:1 Mem:54.66M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 66-100
Fra:1 Mem:54.63M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 63-100
Fra:1 Mem:55.17M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 65-100
Fra:1 Mem:54.87M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 64-100
Fra:1 Mem:54.89M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 69-100
Fra:1 Mem:55.02M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 67-100
Fra:1 Mem:55.04M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 68-100
Fra:1 Mem:54.75M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 72-100
Fra:1 Mem:55.18M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 71-100
Fra:1 Mem:55.36M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 73-100
Fra:1 Mem:55.43M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 70-100
Fra:1 Mem:55.67M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 74-100
Fra:1 Mem:55.39M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 78-100
Fra:1 Mem:55.14M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 76-100
Fra:1 Mem:55.36M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 79-100
Fra:1 Mem:55.48M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 77-100
Fra:1 Mem:55.35M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 80-100
Fra:1 Mem:55.47M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 82-100
Fra:1 Mem:55.04M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 83-100
Fra:1 Mem:55.32M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 81-100
Fra:1 Mem:55.29M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 84-100
Fra:1 Mem:55.27M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 86-100
Fra:1 Mem:55.14M (0.00M, Peak 58.41M) | Time:00:00.15 | Scene, Part 87-100
Fra:1 Mem:55.04M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 88-100
Fra:1 Mem:55.30M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 89-100
Fra:1 Mem:55.26M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 75-100
Fra:1 Mem:55.20M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 91-100
Fra:1 Mem:55.30M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 92-100
Fra:1 Mem:55.46M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 90-100
Fra:1 Mem:55.58M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 93-100
Fra:1 Mem:55.25M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 95-100
Fra:1 Mem:55.50M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 96-100
Fra:1 Mem:55.04M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 98-100
Fra:1 Mem:55.01M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 85-100
Fra:1 Mem:54.59M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 97-100
Fra:1 Mem:54.01M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 100-100
Fra:1 Mem:53.97M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 99-100
Fra:1 Mem:53.88M (0.00M, Peak 58.41M) | Time:00:00.16 | Scene, Part 94-100
Fra:1 Mem:31.80M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing
Fra:1 Mem:31.80M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Determining resolution
Fra:1 Mem:31.80M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Initializing execution
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 1-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 2-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 3-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 4-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 5-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 6-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 7-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 8-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 9-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 1-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 2-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.16 | Compositing | Tile 3-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 4-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 5-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 6-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 7-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 8-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 9-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 1-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 2-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 3-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 4-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 5-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 6-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 7-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 8-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Tile 9-9
Fra:1 Mem:44.16M (0.00M, Peak 58.41M) | Time:00:00.17 | Compositing | Deinitializing execution
Saved: ./Model11_colored/data11_difficultcar/data11_difficultcar_r_216_depth.png0001.png
Saved: ./Model11_colored/data11_difficultcar/data11_difficultcar_r_216_normal.png0001.png
Saved: ./Model11_colored/data11_difficultcar/data11_difficultcar_r_216_albedo.png0001.png
Fra:1 Mem:31.80M (0.00M, Peak 58.41M) | Time:00:00.28 | Sce: Scene Ve:24273 Fa:22152 La:2
Saved: ./Model11_colored/data11_difficultcar/data11_difficultcar_r_216.png
 Time: 00:00.33 (Saving: 00:00.04)


Does this help? and there are no errors as far as I can tell, the terminal just stays open.Also , can u tell , which file are u rendering from? is it Model.obj or Model_normalized.obj, its just that in the ShapeNET dataset, I just find files with this name model_normalized.obj .  

thank you again :) really appreciate it

**Comment by panmari** [comment]
The output you pasted doesn't indicate anything's wrong. Maybe this thread is of help: https://blender.stackexchange.com/questions/24020/importing-obj-with-mtl-and-image-not-working-properly

**Comment by MalihaUCF** [comment]
Hi,

So I figured my problem :+1:  :-) Basically I wasnt using the .mtl file at all whereas this code does require it. The first page which says using a single .obj file and rendering images is kind of misleading if maybe you can modify that and write using xyz.mtl and xyz.obj files to render images.
Otherwise I think this is the best ShapeNET rendering code I have encountered so far and the easiest to use. 
A few more suggestions,maybe you can mention how to download blender via terminal and that the code doesnt require a GPU and the new version 2 of ShapeNET dataset has changed the file names to 

![data12](https://user-images.githubusercontent.com/42460909/48019745-27e05e80-e102-11e8-996d-ceb7cb5fb371.png)

Thanks a lot ! :1st_place_medal: 


My Output now
![new112](https://user-images.githubusercontent.com/42460909/48019962-b9e86700-e102-11e8-98c5-50c0f7e5c028.png)

**Comment by panmari** [comment]
Glad it worked out! 

Can you give the exact invocation you used? I'll adapt the documentation then.

**Comment by MalihaUCF** [comment]
Sure, here this is what I was using

blender --background --python render_blender.py -- --output_folder ./Output0 ./dcdee01d7fe6e1a76ad064d1c5fdd7c/models/model_normalized.obj


< P.S: however, make sure there is a 'model_normalized.mtl' file in the same models folder >
