### ISSUE TITLE
Depth map all ones

### ISSUE THREAD

**Issue by BornInWater** [panmari/stanford-shapenet-renderer#14]
Depth map images generated are all ones. How should I resolve this? The normals and the rendered images seem to be fine but the depth maps are not.

**Comment by panmari** [comment]
1. Can you link the model you tried it with? This makes debugging easier.
2. Try different numbers for the flag depth_scale. This scaling factor determines in what range the depths are and is somewhat specific to the way the model is defined.

**Comment by BornInWater** [comment]
@panmari You mean the obj file?

**Comment by panmari** [comment]
Yes, with model I mean obj file in 1).

**Comment by BornInWater** [comment]
create_data2.obj and corresponding .mtl file in https://github.com/Shade5/3DRPN

Thanks for the help!!

**Comment by panmari** [comment]
The problem is that your obj file defines a full scene (see screenshot attached). The script assumes there's only one object at (0,0,0) that fits the unit cube.

You'll have to fiddle with camera parameters to get the intended behavior.

![screenshot from 2018-12-05 22-52-52](https://user-images.githubusercontent.com/719020/49546482-a4708380-f8e0-11e8-9de2-c07a9c572a4b.png)

**Comment by BornInWater** [comment]
Hey, Can you open this back up again? I closed it by mistake. I am trying out what you suggested and might have some doubts as I go along

**Comment by BornInWater** [comment]
I created an .obj file where I just have a unit cube at (0,0,0), but still I am just getting all 1 in the depth map. I have uploaded the file in https://github.com/Shade5/3DRPN
its cube.obj[and cube.mtl]

**Comment by BornInWater** [comment]
I created an .obj file where I just have a unit cube at (0,0,0), but still I am just getting all 1 in the depth map. I have uploaded the file in https://github.com/Shade5/3DRPN
its cube.obj[and cube.mtl]

**Comment by BornInWater** [comment]
Also, camera, normal and albedo part is working properly. Camera is moving around the 3D world properly and getting proper albedo and normal at each camera location. Depth is not working well. This is true for both single cube at (0,0,0) as well as for a full scenes as well.

**Comment by BornInWater** [comment]
I think i was making some mistake. Its now working with a cube of dimensions less than (1,1,1). Thats fine. I think for a full scene, we can just scale the entire scene to size slightly less than (1,1,1) and then get the depths and later multiply the depth values by the scaling factor. Does that sound proper?

**Comment by panmari** [comment]
Yeah, that should work.
