### ISSUE TITLE
How to get the depth from the depth buffer?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [panmari/stanford-shapenet-renderer#17]
I am new to blender python.
The depth image generated is normalized? right?
So if I want to know the min depth and max depth of the depth image. How to do it?
Best regard,
George Yang

**Comment by panmari** [comment]
What do you mean by "normalized"? 

The script places the object at (0, 0, 0), then places the camera at (0, 1, 0.6) and rotates around the object. The depths produced are to be understood in this coordinate frame. 

For .png images, there's additional scaling to have the depth fit nicely in the range [0, 255]. If you want raw values, specify `--format=OPEN_EXR`. Values there should be between 0 and infinity.

**Comment by panmari** [comment]
Closing due to staleness.
