### ISSUE TITLE
have a problem with run 'blender --background --python render_blender.py -- --output_folder /tmp  --format OPEN_EXR ./Data/model-2.obj'

### ISSUE THREAD

**Issue by Jul-lian** [panmari/stanford-shapenet-renderer#18]
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file ordirectory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Traceback (most recent call last):
  File "/tf/MyWorks/3D/stanford-shapenet-renderer-master/render_blender.py", line 56, in <module>
    links.new(render_layers.outputs['Depth'], depth_file_output.inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Depth" not found'

**Comment by Jul-lian** [comment]
I change use this cmd in docker env had problem as  ,but when change to new env without docker has same problem as such ,"Depth" not foud
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
Traceback (most recent call last):
  File "/home/ad/MyWorks/3D/stanford-shapenet-renderer-master/render_blender.py", line 56, in <module>
    links.new(render_layers.outputs['Depth'], depth_file_output.inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Depth" not found'

**Comment by panmari** [comment]
A lot of this logging is unrelated (from some issues with sound). The last line indicates that you're running on an old blender version. Can you please post the output of `blender --version`?

**Comment by Jul-lian** [comment]
blender --version
Blender 2.76 (sub 0)
        build date: 2016-02-06
        build time: 01:10:10
        build commit date: 1970-01-01
        build commit time: 00:00
        build hash: unknown
        build platform: Linux
        build type: None

**Comment by Jul-lian** [comment]
how can i install blender=2.79 ? i apt-get update then install  via ppa but can only get version=2.76,have other install method?

**Comment by panmari** [comment]
There's instructions e.g. at https://askubuntu.com/questions/4586/is-there-a-ppa-for-the-latest-blender-version. You'll need to add a custom repository.

**Comment by tiancaipipi110** [comment]
@panmari Hi, `blender --background --python render_blender.py -- --output_folder /tmp model.obj` keeps giving me error:
`blender: error: unrecognized arguments: --output_folder model.obj` Any idea what's going on? `model.obj` is at the same folder as `render_blender.py`
