### ISSUE TITLE
How to rotate by X-axis?

### ISSUE THREAD

**Issue by shinxg** [panmari/stanford-shapenet-renderer#19]
Hi @panmari , thanks for sharing rendering code, I got some problems when I tried to rendering shapes while rotating X-axis. I have changed ``b_empty.rotation_euler[2] += radians(stepsize)`` to ``b_empty.rotation_euler[0] += radians(stepsize)``, but the rendered images were not what I expected them to be.

**Comment by hetolin** [comment]
Hi have you solved that problem? I meet the same problem. I have changed `b_empty.rotation_euler[2] += radians(stepsize)` to `b_empty.rotation_euler[0] += radians(stepsize)`, it works, but when I changed `b_empty.rotation_euler[2] += radians(stepsize)` to `b_empty.rotation_euler[1] += radians(stepsize)`, it seems. that the objects didn't rotate at all. I don't know how to deal with it.  @shinxg @panmari

**Comment by ghost** [comment]
Hi, I run into the same problem. Any update?

**Comment by ghost** [comment]
To me it is when rotating around y-axis (rotation_euler[1])
