### ISSUE TITLE
links.new issue

### ISSUE THREAD

**Issue by we1pingyu** [panmari/stanford-shapenet-renderer#21]
Hi, recently when I run your code, an error occurs in the line 65:
in <module>
    links.new(render_layers.outputs['Depth'], map.inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Depth" not found'
So how can I fix it?
Thank you.

**Comment by panmari** [comment]
What version of blender are you using? HEAD is only verified to work with
Blender 2.79.


Am Fr., 29. Nov. 2019 um 04:48 Uhr schrieb ywp <notifications@github.com>:

**Comment by we1pingyu** [comment]
Yes, I run the code on 2.76. And once I change the version to 2.79, the error disappears.
Thank you again.
