### ISSUE TITLE
render script reference

### ISSUE THREAD

**Issue by animebing** [panmari/stanford-shapenet-renderer#26]
@panmari Thanks for providing the render script. I am trying to write some automatic render scripts using blender, but I can't find any useful reference about the usage that is used in your script. Although I know there is blender python API documentation, it doesn't seem to help. Would you mind providing me with some material or tutorial to write render script with blender using python, thanks for your kind help.

**Comment by panmari** [comment]
My workflow was

1. Trying it out in Blender UI, stitching a render graph together there until I had the desired output.
2. Translating my graph to code.
3. When things broke unexpectedly, asked at https://blender.stackexchange.com/
