### ISSUE TITLE
blender Unable to open a display

### ISSUE THREAD

**Issue by sunny123123** [panmari/stanford-shapenet-renderer#28]
I know nothing about blender. I just want generate some different views pictures with one obj file. My blender is 2.90.0. I got below error when I run command
```
blender --background --python render_blender.py -- --output_folder temp bugatti.obj
```

```
Blender 2.90.0 (hash 0330d1af29c0 built 2020-08-31 11:54:54)
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
/run/user/1000/gvfs/ non-existent directory
found bundled python: /home/inveno/payne/3d/blender-2.90.0-linux64/2.90/python
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
(  0.0001 sec |   0.0001 sec) Importing OBJ 'bugatti.obj'...
  (  0.0002 sec |   0.0001 sec) Parsing OBJ file...
    ( 18.7100 sec |  18.7098 sec) Done, loading materials and images...
    ( 18.7277 sec |  18.7275 sec) Done, building geometries (verts:744213 faces:759882 materials: 40 smoothgroups:1) ...
    ( 35.2136 sec |  35.2135 sec) Done.
  ( 35.2138 sec |  35.2137 sec) Finished importing: 'bugatti.obj'
Progress: 100.00%

Info: Removed 2672 vertice(s)
Info: Removed 2672 vertice(s)
Rotation 0.0, 0.0
Unable to open a display
```
Any suggestions will help me , thanks

**Comment by mvoelk** [comment]
ALSA is related to audio and is not a blender specific issue. It actually means what is written there, no audio device found. Maybe a driver issue...

**Comment by sunny123123** [comment]
@mvoelk  thanks for your reply. I will try resolve the ALSA question. But I think the key point is **Unable to open a display**. I forgot to add that my OS is **ubuntu 18.04**

**Comment by mvoelk** [comment]
It typically means there is no x server running, but I'm not sure if it is required...

**Comment by panmari** [comment]
1. Do you have Xorg installed on the machine you're trying this?
2. According to [this](https://github.com/nytimes/rd-blender-docker/issues/6), switching to the "cycles" renderer might be an option. Try the same command with `--engine=CYCLES`.

**Comment by ldo** [comment]
You can probably get rid of the error messages about audio by adding the “`-noaudio`” option to the Blender command.

**Comment by michimussato** [comment]
@panmari this is just to let you know that your workaround `--engine=CYCLES` will fail in case you render grease pencil elements - even in Cycles.
@sunny123123 , a more reliable solution can be found here: https://github.com/nytimes/rd-blender-docker/issues/6#issuecomment-1296347978
