### ISSUE TITLE
additional images

### ISSUE THREAD

**Issue by concrete13377** [panmari/stanford-shapenet-renderer#29]
Hello! Thanks for your repository. I want to render the whole shapenet, and it takes a lot of time. I would like to know if it takes time to create and save additional images (depth, albedo, normal and id maps) and if yes how can I avoid wasting this time

**Comment by panmari** [comment]
You can comment out the nodes that create the additional images, e.g. [here](https://github.com/panmari/stanford-shapenet-renderer/blob/5ddf7e9e13e1e6067daddc66fd74e7fc45e3b7f5/render_blender.py#L106)
