### ISSUE TITLE
truncated depth images

### ISSUE THREAD

**Issue by ywpkwon** [panmari/stanford-shapenet-renderer#3]
For me, the `depth` image looks truncated for some reason while `normal` and `albedo` seem fine. Is there any threshold? Could you please advise me how I can solve this?

![100715345ee54d7ae38b52b4ee9d36a3_r_002_albedo0001](https://user-images.githubusercontent.com/18429284/28294691-87bfa4b4-6b10-11e7-9f67-032752cd0ce8.png)
![100715345ee54d7ae38b52b4ee9d36a3_r_002_depth0001](https://user-images.githubusercontent.com/18429284/28294695-974bf608-6b10-11e7-8aff-f3d2a8d8ae61.png)

**Comment by panmari** [comment]
See comment [here](https://github.com/panmari/stanford-shapenet-renderer/blob/master/render_blender.py#L46). Depending on the size of your objects, you might want to adapt the parameter `map.size` to give you a nice depth map. If that fixes your problem, I'll create a CL that makes this easier configurable.

**Comment by ywpkwon** [comment]
Yes. I solved using that. However, it seems smaller `map.size` value render further depth (Is that right?) I am still not getting the meaning of the `map.size`.

**Comment by ywpkwon** [comment]
Although I am thinking this tool is so great, I imagine it would be better if there is an easy configuration about `camera position`, `angle_step`, etc. at one place. (This may be personal because of my no background about Blender, though.)

**Comment by panmari** [comment]
I don't exactly remember, but if the value is extreme to one side, the whole depth gets flat, in other word the depth map is just gray. The other extreme is the one you ran into, where the depth map gets truncated.

**Comment by panmari** [comment]
Added --depth_scale parameter.

**Comment by panmari** [comment]
'angle_step', i. e. how much the camera should turn for each picture, can be control through the 'views' parameter. So if you increase 'views', 'angle_step' will be smaller and producer more images. 

For the problem with light sources I don't have any good solution. Depending on your models, your experience will be vastly different, so I guess some hand-tuning will always be necessary there :(

**Comment by ywpkwon** [comment]
Thank you so much!

**Comment by Amir-Arsalan** [comment]
@panmari @ywpkwon I also encountered the same issue. I wonder, why not setting the scale parameter to 1 as it seems to resolve the issue?

**Comment by Amir-Arsalan** [comment]
Maybe setting `depth_scale` to `1` works for me because I am using the ShapeNet Core data set. All 3D shapes in that data set are normalized. What do you think @ywpkwon and @panmari?
