### ISSUE TITLE
Batch rendering with Windows

### ISSUE THREAD

**Issue by Benjamin-BB** [panmari/stanford-shapenet-renderer#32]
Hey, thanks for the code. I was wondering if anyone had any idea on how to do the batch rendering on windows ? I have struggled to find a solution.

**Comment by panmari** [comment]
Sorry, I'm not familiar with the windows shell... Maybe somebody else could chime in?

**Comment by Benjamin-BB** [comment]
I ended up coding the batch rendering with python
