### ISSUE TITLE
How to use the generated depth map and normal map?

### ISSUE THREAD

**Issue by Yuliang-Zou** [panmari/stanford-shapenet-renderer#5]
Hi @panmari , thanks for sharing the code.

Since I am not familiar with blender and rendering, I wonder how can I get the accurate depth and normal values from the generation. Seems that they are all scaled to [0, 255].

And I also wonder how can I get the camera parameters (i.e. intrinsics and extrinsics).

**Comment by panmari** [comment]
See PR #7 for increasing resolution of depth map. 

Not sure about camera parameters. It's pretty much the default blender camera, rotated around origin.
