### ISSUE TITLE
Getting float depth

### ISSUE THREAD

**Issue by Amir-Arsalan** [panmari/stanford-shapenet-renderer#6]
I wonder, is it possible to get float depth maps as well instead of int?

**Comment by Amir-Arsalan** [comment]
@panmari Maybe this can help:

https://blender.stackexchange.com/questions/65526/saving-z-data-linearly-accurate-depth-map

I wonder, would it be possible to render accurate depth maps using your code?

**Comment by panmari** [comment]
I added an option to increase the depth of the output from 8 bit to 16 bit. This should give you a much more accurate depth map. See pull request #7. Would this satisfy your needs?

**Comment by Amir-Arsalan** [comment]
@panmari Thank you. Does that mean that the numbers save into the final image will now range from `1` to `2^16-1`? If that's the case, then I would say the problem should be solved.

**Comment by panmari** [comment]
Yes exactly.

**Comment by Amir-Arsalan** [comment]
@panmari I wonder, is there a reason why you did not merge the pull request with the main code? Have you tested the last changes yourself?

**Comment by panmari** [comment]
I only tested it with bleeding edge blender. I wanted to test it as well
with blender included in the debian repository.
