### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Depth" not found'

### ISSUE THREAD

**Issue by howard84527** [panmari/stanford-shapenet-renderer#8]
I wanted to render my obj data but I got an error below:

Traceback (most recent call last):
  File "/home/howard/TF_14/Render_data/stanford-shapenet-renderer/render_blender.py", line 65, in <module>
    links.new(render_layers.outputs['Depth'], map.inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Depth" not found'

Blender quit

**Comment by panmari** [comment]
Hi, thanks for the report. What version of Blender are you using?

**Comment by howard84527** [comment]
I updated to 2.79 and solved the problem, but the .png pics could't see any shape which I rendered my own data. There were just background.

Thank you

**Comment by panmari** [comment]
It might be that your object is too big or too small. DId you try different parameters for the `--scale` option?

**Comment by hzxie** [comment]
If you use old versions of Blender, try to replace `Depth` with `Z`.

**Comment by panmari** [comment]
Thanks for the work-around hzxie. Closing the issue due to inactivity.
